name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: "Build ${{ matrix.image.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: mhaii/s3sync
            path: .
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Detect changes
        uses: dorny/paths-filter@v2.10.2
        id: filter
        if: github.event_name != 'workflow_dispatch'
        with:
          filters: |
            build:
              - ${{ matrix.image.path }}/!(**.md)
      - name: Docker Metadata
        uses: docker/metadata-action@v4.0.1
        id: meta
        if: (github.event_name == 'workflow_dispatch' || steps.filter.outputs.build == 'true') || ( github.event_name == 'release' && github.event.action == 'published' )
        with:
          images: ${{ matrix.image.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        if: (github.event_name == 'workflow_dispatch' || steps.filter.outputs.build == 'true') || ( github.event_name == 'release' && github.event.action == 'published' )
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2.0.0
        if: (github.event_name == 'workflow_dispatch' || steps.filter.outputs.build == 'true') || ( github.event_name == 'release' && github.event.action == 'published' )
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        if: ( (github.event_name == 'workflow_dispatch' || steps.filter.outputs.build == 'true') && github.event_name != 'pull_request' ) || ( github.event_name == 'release' && github.event.action == 'published' )
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.1.1
        if: (github.event_name == 'workflow_dispatch' || steps.filter.outputs.build == 'true') || ( github.event_name == 'release' && github.event.action == 'published' )
        with:
          context: ${{ matrix.image.path }}
          platforms: ${{ matrix.image.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
